settings:
  availabilityFactor: 0.9
  # fakeBad: 123456
  power: 1000000000.0
  cycleLength: 411.11
  loadingFile: c5g7-blueprints.yaml
  nCycles: 10
  burnSteps: 2
  buGroups:
    - 100
  comment: C5G7 LWR Benchmark inputs
  genXS: Neutron
  numProcessors: 1
  genReports: false
  versions:
    armi: uncontrolled
  verbosity: info
  OpenMCExePath: openmc
  energyMode: continuous-energy
  openmcVerbosity: 7
  nParticles: 10000
  nBatches: 300
  nInactiveBatches: 10
  groupStructure: "CINDER63"
  tallyMeshDimension: [1000,1000,1]
  entropyMeshDimension: [4,4,4]
  nOMPThreads: 72
  nMPIProcesses: 1
  verticalSymmetry: True
